plugins:
  - uses:
    - plugin: ubiquity-os-marketplace/daemon-disqualifier@main
      with:
        warning: "7 days"
        pullRequestRequired: false
        eventWhitelist:
          - 'pull_request.review_requested'
          - 'pull_request.ready_for_review'
          - 'pull_request_review_comment.created'
          - 'issue_comment.created'
          - 'push'
        disqualification: "14 days"
